### ISSUE TITLE
pixelbook is not booting from USB flash drive

### ISSUE THREAD

**Issue by TArtiushenko** [eupnea-linux/eupnea#4]
I've flashed the USB flash drive with your tool but my pixelbook doesn't boot from it.
Tested with chromeOS recovery on the same flash drive - everything works.

**Comment by WeirdTreeThing** [comment]
@TArtiushenko Can you join the discord for support?

**Comment by Apacelus** [comment]
Did you use direct write or did you flash an image?

Are you building from crostini?

Can you try the following: restart your builder pc, then delete the old eupnea folder, rerun the install command. If it still doesnt work, can you send the output of ``sudo ls -a /path-to-mounted-usb``

**Comment by TArtiushenko** [comment]
I used another linux (Arch) laptop, flashed with etcher (tried with dd - same result)
Restarted the laptop and deleted the eupnea folder and now trying to flash using the "direct" method but it takes forever - waiting almost 3 hours

**Comment by Apacelus** [comment]
Which distro and desktop environment are you trying to build?

**Comment by TArtiushenko** [comment]
Arch KDE

**Comment by Apacelus** [comment]
Hmm, I just created a usb myself and tested it on my braswell and tigerlake chromebooks, both devices boot. Can you perhaps try the the direct write option?

**Comment by TArtiushenko** [comment]
I even tried to change usb 2 to usb 3 port, but still takes to long, after 3-4 hours i cancelled the process.
Stuck on "installing kde"

**Comment by Apacelus** [comment]
That is a bit weird. Try the cli option as your DE. Also, try another usb.

**Comment by TArtiushenko** [comment]
today i have this error

`==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.
Traceback (most recent call last):
  File "/home/taras/eupnea/./build.py", line 459, in <module>
    prepare_host(user_input[0])
  File "/home/taras/eupnea/./build.py", line 70, in prepare_host
    bash("cd cgpt-bin && makepkg -sirc --noconfirm")
  File "/home/taras/eupnea/functions.py", line 112, in bash
    return subprocess.check_output(command, shell=True, text=True).strip()
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd cgpt-bin && makepkg -sirc --noconfirm' returned non-zero exit status 10.`

**Comment by Apacelus** [comment]
Yea, thats a known issue. Install cgpt and vboot-utils(if you havent yet) and git pull the repo

**Comment by Apacelus** [comment]
@TArtiushenko Can you try building again and see if you have any luck this time? I have made several new commits over the last few days.

**Comment by TArtiushenko** [comment]
The package cgpt-bin seems to be broken in aur arch Linux

**Comment by Apacelus** [comment]
Use this [PKGFILE](https://github.com/eupnea-linux/eupnea/blob/main/configs/PKGBUILD)

**Comment by TArtiushenko** [comment]
Now it works.
But doesn't boot from usb 3.0, but i have such issue with other devices

**Comment by Apacelus** [comment]
Thats wonderful news!

**Comment by TArtiushenko** [comment]
Yes but still lot of problems: no audio, no brightness control, no key backlight, wrong function key mapping...

**Comment by Apacelus** [comment]
> no audio  

wait for AVS.
> no brightness control

Uhhh, shouldnt be the case... Can you provide more details?

> no keyboard backlight

How did you try to turn it on?
> wrong function key mapping

Gonna be fixed in the future

**Comment by Apacelus** [comment]
There is no Ubuntu built in keyboard backlight shortcut. Youll need to use a gnome extension for that. Or set this as a custom shortcut:
```
gdbus call --session --dest org.gnome.SettingsDaemon.Power --object-path /org/gnome/SettingsDaemon/Power --method org.gnome.SettingsDaemon.Power.Keyboard.StepUp

gdbus call --session --dest org.gnome.SettingsDaemon.Power --object-path /org/gnome/SettingsDaemon/Power --method org.gnome.SettingsDaemon.Power.Keyboard.StepDown
```

**Comment by Apacelus** [comment]
As for the rest, it seems there is a repo for that: https://github.com/flantel/pixelbook-linux#running-the-install-script

Perhaps Ill reverseengineer it and integrated it into eupnea at some point
