### ISSUE TITLE
Cannot run build.py; seems to require Python 3.10.

### ISSUE THREAD

**Issue by viniciusferrao** [eupnea-linux/eupnea#7]
Hello, when trying to run build.py the following is returned:

```
# ./build.py 
  File "./build.py", line 247
    match distro_name:
          ^
SyntaxError: invalid syntax
```

OS info:

```
[root@localhost eupnea]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.5 (Ootpa)
[root@localhost eupnea]# python3 --version
Python 3.8.8
```

Looking around the issue may be that Python 3.10 is required. If this is correct I think `docs` should point this. Crostini also fails with the same error.

Thanks.

**Comment by WeirdTreeThing** [comment]
This does require python 3.10 to run. I'm not sure if redhat linux will work though.

**Comment by Apacelus** [comment]
I tried to implement a python check, but the compiler reads the whole script before executing my check for some reason...

I even wrote the code to update to python 3.10 for debian(Crostini)

**Comment by Apacelus** [comment]
Should be now fixed as of https://github.com/eupnea-linux/eupnea/commit/73075edfbe4d483c1eaabe08754e04c6828d11f5

**Comment by khawkins98** [comment]
> Crostini also fails with the same error.

Just a note that after the ChromeOS Debian 11 update, this was no longer an issue. Crostini was able to proceed with installing python 3.10.
